use_frameworks!

platform :ios, '11.0'

target 'LDURLRouter_Example' do
  pod 'LDURLRouter', :path => '../'

  target 'LDURLRouter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
